// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "zahid.cakici@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fixtures": {
            "get": {
                "description": "Returns all fixtures across all weeks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fixtures"
                ],
                "summary": "Get all fixtures",
                "responses": {
                    "200": {
                        "description": "Success response with fixtures array",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.FixturesListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/fixtures/generate": {
            "post": {
                "description": "Creates a round-robin fixture schedule for all teams (6 weeks, home and away)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fixtures"
                ],
                "summary": "Generate fixtures",
                "responses": {
                    "200": {
                        "description": "Success response with generated fixtures",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.FixturesListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/fixtures/{week}": {
            "get": {
                "description": "Returns all fixtures for a specific week number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fixtures"
                ],
                "summary": "Get fixtures by week",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Week number (1-6)",
                        "name": "week",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response with fixtures for the week",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.FixturesListResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid week number",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/predictions": {
            "get": {
                "description": "Returns the probability of each team winning the championship (available from week 4)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Standings"
                ],
                "summary": "Get championship predictions",
                "responses": {
                    "200": {
                        "description": "Success response with predictions array",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.PredictionsListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/simulation/match/{id}": {
            "put": {
                "description": "Manually update the score of a specific match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Simulation"
                ],
                "summary": "Update match result",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Match ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Match score update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.UpdateMatchResultRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success response with updated simulation state",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.SimulationStateFullResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid match ID or request body",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/simulation/play-all": {
            "post": {
                "description": "Simulates all remaining matches until the season is complete",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Simulation"
                ],
                "summary": "Play all remaining weeks",
                "responses": {
                    "200": {
                        "description": "Success response with final simulation state",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.SimulationStateFullResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (e.g., season already complete)",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/simulation/play-week": {
            "post": {
                "description": "Simulates all matches for the next week and returns updated state",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Simulation"
                ],
                "summary": "Play next week",
                "responses": {
                    "200": {
                        "description": "Success response with updated simulation state",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.SimulationStateFullResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request (e.g., no more weeks to play)",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/simulation/reset": {
            "post": {
                "description": "Resets all match results and league state while keeping fixtures",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Simulation"
                ],
                "summary": "Reset simulation",
                "responses": {
                    "200": {
                        "description": "Success response with reset confirmation",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/simulation/state": {
            "get": {
                "description": "Returns the complete current state including standings, predictions, and match results",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Simulation"
                ],
                "summary": "Get simulation state",
                "responses": {
                    "200": {
                        "description": "Success response with full simulation state",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.SimulationStateFullResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/standings": {
            "get": {
                "description": "Returns the current league table with points, goals, and positions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Standings"
                ],
                "summary": "Get league standings",
                "responses": {
                    "200": {
                        "description": "Success response with standings array",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.StandingsListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "description": "Returns all teams participating in the tournament with their power ratings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Get all teams",
                "responses": {
                    "200": {
                        "description": "Success response with teams array",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.TeamsListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.APIErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handlers.APIErrorResponse": {
            "description": "Standard API error response",
            "type": "object",
            "properties": {
                "error": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "Something went wrong"
                }
            }
        },
        "internal_handlers.ChampionshipPredictionResponse": {
            "description": "Championship prediction for a team",
            "type": "object",
            "properties": {
                "percentage": {
                    "type": "number",
                    "example": 45.5
                },
                "teamId": {
                    "type": "integer",
                    "example": 1
                },
                "teamName": {
                    "type": "string",
                    "example": "Manchester City"
                }
            }
        },
        "internal_handlers.FixturesListResponse": {
            "description": "List of all fixtures",
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers.MatchResponse"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_handlers.LeagueStateResponse": {
            "description": "Current league state",
            "type": "object",
            "properties": {
                "completed": {
                    "type": "boolean",
                    "example": false
                },
                "currentWeek": {
                    "type": "integer",
                    "example": 3
                },
                "fixturesCreated": {
                    "type": "boolean",
                    "example": true
                },
                "started": {
                    "type": "boolean",
                    "example": true
                },
                "totalWeeks": {
                    "type": "integer",
                    "example": 6
                }
            }
        },
        "internal_handlers.MatchResponse": {
            "description": "Match information",
            "type": "object",
            "properties": {
                "awayScore": {
                    "type": "integer",
                    "example": 1
                },
                "awayTeam": {
                    "$ref": "#/definitions/internal_handlers.TeamResponse"
                },
                "homeScore": {
                    "type": "integer",
                    "example": 2
                },
                "homeTeam": {
                    "$ref": "#/definitions/internal_handlers.TeamResponse"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "played": {
                    "type": "boolean",
                    "example": true
                },
                "week": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_handlers.MatchResultResponse": {
            "description": "Match result",
            "type": "object",
            "properties": {
                "awayScore": {
                    "type": "integer",
                    "example": 1
                },
                "awayTeamName": {
                    "type": "string",
                    "example": "Arsenal"
                },
                "homeScore": {
                    "type": "integer",
                    "example": 2
                },
                "homeTeamName": {
                    "type": "string",
                    "example": "Chelsea"
                }
            }
        },
        "internal_handlers.MessageData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                }
            }
        },
        "internal_handlers.MessageResponse": {
            "description": "Simple message response",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_handlers.MessageData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_handlers.PredictionsListResponse": {
            "description": "Championship predictions",
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers.ChampionshipPredictionResponse"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_handlers.SimulationStateFullResponse": {
            "description": "Full simulation state response",
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_handlers.SimulationStateResponse"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_handlers.SimulationStateResponse": {
            "description": "Complete simulation state including standings and predictions",
            "type": "object",
            "properties": {
                "allMatches": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/internal_handlers.MatchResultResponse"
                        }
                    }
                },
                "currentWeekResults": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers.MatchResultResponse"
                    }
                },
                "leagueState": {
                    "$ref": "#/definitions/internal_handlers.LeagueStateResponse"
                },
                "predictions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers.ChampionshipPredictionResponse"
                    }
                },
                "standings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers.TeamStandingResponse"
                    }
                }
            }
        },
        "internal_handlers.StandingsListResponse": {
            "description": "Current league standings",
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers.TeamStandingResponse"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_handlers.TeamResponse": {
            "description": "Team information",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Manchester City"
                },
                "power": {
                    "type": "integer",
                    "example": 90
                }
            }
        },
        "internal_handlers.TeamStandingResponse": {
            "description": "Team standing in league table",
            "type": "object",
            "properties": {
                "drawn": {
                    "type": "integer",
                    "example": 1
                },
                "goalDifference": {
                    "type": "integer",
                    "example": 4
                },
                "goalsAgainst": {
                    "type": "integer",
                    "example": 3
                },
                "goalsFor": {
                    "type": "integer",
                    "example": 7
                },
                "lost": {
                    "type": "integer",
                    "example": 0
                },
                "played": {
                    "type": "integer",
                    "example": 3
                },
                "points": {
                    "type": "integer",
                    "example": 7
                },
                "teamId": {
                    "type": "integer",
                    "example": 1
                },
                "teamName": {
                    "type": "string",
                    "example": "Manchester City"
                },
                "won": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "internal_handlers.TeamsListResponse": {
            "description": "List of all teams",
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handlers.TeamResponse"
                    }
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_handlers.UpdateMatchResultRequest": {
            "description": "Request body for updating match scores",
            "type": "object",
            "properties": {
                "awayScore": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 1
                },
                "homeScore": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 2
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Champions League Simulation API",
	Description:      "A REST API for simulating a Champions League tournament",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
